import { buildSync } from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

const resolveModule = createRequire(import.meta.url);
const leafletDir = path.dirname(resolveModule.resolve("leaflet/package.json"));
const clusterDir = path.dirname(resolveModule.resolve("leaflet.markercluster/package.json"));
const css = fs.readFileSync(path.join(leafletDir, "dist/leaflet.css"), "utf8")
  + fs.readFileSync(path.join(clusterDir, "dist/MarkerCluster.css"), "utf8")
  .replace(/url\(images\/([^)]*)\)/g, (_, file) =>
    `url(data:image/png;base64,${fs.readFileSync(path.join(leafletDir, "dist/images", file)).toString("base64")})`);
const result = buildSync({
  entryPoints: ["src/map/leaflet-runtime.ts"], bundle: true, minify: true,
  platform: "browser", format: "iife", target: "es2020", write: false,
  legalComments: "inline",
});
const output = "// Generated by pnpm build:map. Do not edit. Includes Leaflet (BSD-2-Clause) and Leaflet.markercluster (MIT).\n"
  + `export const leafletScript = ${JSON.stringify(result.outputFiles[0].text)};\n`
  + `export const leafletCss = ${JSON.stringify(css)};\n`;
fs.writeFileSync("src/map/leaflet-assets.generated.ts", output);
console.log("Bundled Leaflet and map runtime for offline startup.");
