/**
 * Generates src/data/tileLoader.ts with static require() calls for each tile.
 * Metro bundler needs static paths — no dynamic require().
 *
 * Usage: npx tsx scripts/gen-tile-loader.ts
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const tilesDir = path.join(__dirname, "..", "src", "data", "tiles");
const outPath = path.join(__dirname, "..", "src", "data", "tileLoader.ts");

// Only load tiles in the current snapshot, not stale files from older imports.
const index: { tiles: { key: string }[] } = JSON.parse(fs.readFileSync(path.join(tilesDir, "..", "tile-index.json"), "utf8"));
const files = index.tiles.map(tile => `tile_${tile.key}.json`).sort();
for (const file of files) {
  if (!fs.existsSync(path.join(tilesDir, file))) throw new Error(`Missing current tile: ${file}`);
}

const lines: string[] = [
  "// Auto-generated by scripts/gen-tile-loader.ts — do not edit manually",
  "import { Toilet } from '../types/toilet';",
  "",
  "type RawToilet = Omit<Toilet, 'category'> & { category: string };",
  "",
  "const tileMap: Record<string, () => RawToilet[]> = {",
];

for (const file of files) {
  const key = file.replace("tile_", "").replace(".json", "");
  lines.push(`  '${key}': () => require('./tiles/${file}'),`);
}

lines.push("};");
lines.push("");
lines.push(`/**`);
lines.push(
  ` * Returns the tile keys needed to cover a ~25km radius around the given coordinates.`,
);
lines.push(` */`);
lines.push(`function getNeededTileKeys(lat: number, lon: number): string[] {`);
lines.push(`  const keys: string[] = [];`);
lines.push(`  // Load the tile containing the point plus all 8 neighbors`);
lines.push(`  const baseLat = Math.floor(lat);`);
lines.push(`  const baseLon = Math.floor(lon);`);
lines.push(`  for (let dLat = -1; dLat <= 1; dLat++) {`);
lines.push(`    for (let dLon = -1; dLon <= 1; dLon++) {`);
lines.push("      const key = `${baseLat + dLat}_${baseLon + dLon}`;");
lines.push(`      if (tileMap[key]) keys.push(key);`);
lines.push(`    }`);
lines.push(`  }`);
lines.push(`  return keys;`);
lines.push(`}`);
lines.push("");
lines.push(`/**`);
lines.push(` * Loads toilets from relevant tiles near the given coordinates.`);
lines.push(` */`);
lines.push(
  `export function loadNearbyTiles(lat: number, lon: number): RawToilet[] {`,
);
lines.push(`  const keys = getNeededTileKeys(lat, lon);`);
lines.push(`  const all: RawToilet[] = [];`);
lines.push(`  for (const key of keys) {`);
lines.push(`    all.push(...tileMap[key]());`);
lines.push(`  }`);
lines.push(`  return all;`);
lines.push(`}`);
lines.push("");
lines.push(`/**`);
lines.push(` * Loads toilets from all tiles that overlap the given bounding box.`);
lines.push(` */`);
lines.push(`export function loadTilesInBounds(`);
lines.push(`  latMin: number,`);
lines.push(`  latMax: number,`);
lines.push(`  lonMin: number,`);
lines.push(`  lonMax: number,`);
lines.push(`): RawToilet[] {`);
lines.push(`  const all: RawToilet[] = [];`);
lines.push(`  const minTileLat = Math.floor(latMin);`);
lines.push(`  const maxTileLat = Math.floor(latMax);`);
lines.push(`  const minTileLon = Math.floor(lonMin);`);
lines.push(`  const maxTileLon = Math.floor(lonMax);`);
lines.push(``);
lines.push(`  for (let tLat = minTileLat; tLat <= maxTileLat; tLat++) {`);
lines.push(`    for (let tLon = minTileLon; tLon <= maxTileLon; tLon++) {`);
lines.push("      const key = `${tLat}_${tLon}`;");
lines.push(`      if (tileMap[key]) {`);
lines.push(`        all.push(...tileMap[key]());`);
lines.push(`      }`);
lines.push(`    }`);
lines.push(`  }`);
lines.push(`  return all;`);
lines.push(`}`);
lines.push("");

fs.writeFileSync(outPath, lines.join("\n"));
console.log(`Generated tileLoader.ts with ${files.length} tiles`);
