// Auto-generated by scripts/gen-tile-loader.ts — do not edit manually
import { Toilet } from '../types/toilet';

type RawToilet = { id: string; lat: number; lon: number; name: string; city: string; category: string; tags: string[]; opening_hours?: string; operator?: string; fee?: string };

const tileMap: Record<string, () => RawToilet[]> = {
  '45_10': () => require('./tiles/tile_45_10.json'),
  '45_11': () => require('./tiles/tile_45_11.json'),
  '45_12': () => require('./tiles/tile_45_12.json'),
  '45_13': () => require('./tiles/tile_45_13.json'),
  '45_14': () => require('./tiles/tile_45_14.json'),
  '45_15': () => require('./tiles/tile_45_15.json'),
  '45_16': () => require('./tiles/tile_45_16.json'),
  '45_17': () => require('./tiles/tile_45_17.json'),
  '45_5': () => require('./tiles/tile_45_5.json'),
  '45_6': () => require('./tiles/tile_45_6.json'),
  '45_7': () => require('./tiles/tile_45_7.json'),
  '45_8': () => require('./tiles/tile_45_8.json'),
  '45_9': () => require('./tiles/tile_45_9.json'),
  '46_10': () => require('./tiles/tile_46_10.json'),
  '46_11': () => require('./tiles/tile_46_11.json'),
  '46_12': () => require('./tiles/tile_46_12.json'),
  '46_13': () => require('./tiles/tile_46_13.json'),
  '46_14': () => require('./tiles/tile_46_14.json'),
  '46_15': () => require('./tiles/tile_46_15.json'),
  '46_16': () => require('./tiles/tile_46_16.json'),
  '46_17': () => require('./tiles/tile_46_17.json'),
  '46_5': () => require('./tiles/tile_46_5.json'),
  '46_6': () => require('./tiles/tile_46_6.json'),
  '46_7': () => require('./tiles/tile_46_7.json'),
  '46_8': () => require('./tiles/tile_46_8.json'),
  '46_9': () => require('./tiles/tile_46_9.json'),
  '47_10': () => require('./tiles/tile_47_10.json'),
  '47_11': () => require('./tiles/tile_47_11.json'),
  '47_12': () => require('./tiles/tile_47_12.json'),
  '47_13': () => require('./tiles/tile_47_13.json'),
  '47_14': () => require('./tiles/tile_47_14.json'),
  '47_15': () => require('./tiles/tile_47_15.json'),
  '47_16': () => require('./tiles/tile_47_16.json'),
  '47_17': () => require('./tiles/tile_47_17.json'),
  '47_5': () => require('./tiles/tile_47_5.json'),
  '47_6': () => require('./tiles/tile_47_6.json'),
  '47_7': () => require('./tiles/tile_47_7.json'),
  '47_8': () => require('./tiles/tile_47_8.json'),
  '47_9': () => require('./tiles/tile_47_9.json'),
  '48_10': () => require('./tiles/tile_48_10.json'),
  '48_11': () => require('./tiles/tile_48_11.json'),
  '48_12': () => require('./tiles/tile_48_12.json'),
  '48_13': () => require('./tiles/tile_48_13.json'),
  '48_14': () => require('./tiles/tile_48_14.json'),
  '48_15': () => require('./tiles/tile_48_15.json'),
  '48_16': () => require('./tiles/tile_48_16.json'),
  '48_17': () => require('./tiles/tile_48_17.json'),
  '48_5': () => require('./tiles/tile_48_5.json'),
  '48_6': () => require('./tiles/tile_48_6.json'),
  '48_7': () => require('./tiles/tile_48_7.json'),
  '48_8': () => require('./tiles/tile_48_8.json'),
  '48_9': () => require('./tiles/tile_48_9.json'),
  '49_10': () => require('./tiles/tile_49_10.json'),
  '49_11': () => require('./tiles/tile_49_11.json'),
  '49_12': () => require('./tiles/tile_49_12.json'),
  '49_13': () => require('./tiles/tile_49_13.json'),
  '49_14': () => require('./tiles/tile_49_14.json'),
  '49_15': () => require('./tiles/tile_49_15.json'),
  '49_16': () => require('./tiles/tile_49_16.json'),
  '49_17': () => require('./tiles/tile_49_17.json'),
  '49_5': () => require('./tiles/tile_49_5.json'),
  '49_6': () => require('./tiles/tile_49_6.json'),
  '49_7': () => require('./tiles/tile_49_7.json'),
  '49_8': () => require('./tiles/tile_49_8.json'),
  '49_9': () => require('./tiles/tile_49_9.json'),
  '50_10': () => require('./tiles/tile_50_10.json'),
  '50_11': () => require('./tiles/tile_50_11.json'),
  '50_12': () => require('./tiles/tile_50_12.json'),
  '50_13': () => require('./tiles/tile_50_13.json'),
  '50_14': () => require('./tiles/tile_50_14.json'),
  '50_15': () => require('./tiles/tile_50_15.json'),
  '50_16': () => require('./tiles/tile_50_16.json'),
  '50_17': () => require('./tiles/tile_50_17.json'),
  '50_5': () => require('./tiles/tile_50_5.json'),
  '50_6': () => require('./tiles/tile_50_6.json'),
  '50_7': () => require('./tiles/tile_50_7.json'),
  '50_8': () => require('./tiles/tile_50_8.json'),
  '50_9': () => require('./tiles/tile_50_9.json'),
  '51_10': () => require('./tiles/tile_51_10.json'),
  '51_11': () => require('./tiles/tile_51_11.json'),
  '51_12': () => require('./tiles/tile_51_12.json'),
  '51_13': () => require('./tiles/tile_51_13.json'),
  '51_14': () => require('./tiles/tile_51_14.json'),
  '51_15': () => require('./tiles/tile_51_15.json'),
  '51_16': () => require('./tiles/tile_51_16.json'),
  '51_17': () => require('./tiles/tile_51_17.json'),
  '51_5': () => require('./tiles/tile_51_5.json'),
  '51_6': () => require('./tiles/tile_51_6.json'),
  '51_7': () => require('./tiles/tile_51_7.json'),
  '51_8': () => require('./tiles/tile_51_8.json'),
  '51_9': () => require('./tiles/tile_51_9.json'),
  '52_10': () => require('./tiles/tile_52_10.json'),
  '52_11': () => require('./tiles/tile_52_11.json'),
  '52_12': () => require('./tiles/tile_52_12.json'),
  '52_13': () => require('./tiles/tile_52_13.json'),
  '52_14': () => require('./tiles/tile_52_14.json'),
  '52_15': () => require('./tiles/tile_52_15.json'),
  '52_16': () => require('./tiles/tile_52_16.json'),
  '52_17': () => require('./tiles/tile_52_17.json'),
  '52_5': () => require('./tiles/tile_52_5.json'),
  '52_6': () => require('./tiles/tile_52_6.json'),
  '52_7': () => require('./tiles/tile_52_7.json'),
  '52_8': () => require('./tiles/tile_52_8.json'),
  '52_9': () => require('./tiles/tile_52_9.json'),
  '53_10': () => require('./tiles/tile_53_10.json'),
  '53_11': () => require('./tiles/tile_53_11.json'),
  '53_12': () => require('./tiles/tile_53_12.json'),
  '53_13': () => require('./tiles/tile_53_13.json'),
  '53_14': () => require('./tiles/tile_53_14.json'),
  '53_15': () => require('./tiles/tile_53_15.json'),
  '53_16': () => require('./tiles/tile_53_16.json'),
  '53_17': () => require('./tiles/tile_53_17.json'),
  '53_5': () => require('./tiles/tile_53_5.json'),
  '53_6': () => require('./tiles/tile_53_6.json'),
  '53_7': () => require('./tiles/tile_53_7.json'),
  '53_8': () => require('./tiles/tile_53_8.json'),
  '53_9': () => require('./tiles/tile_53_9.json'),
  '54_10': () => require('./tiles/tile_54_10.json'),
  '54_11': () => require('./tiles/tile_54_11.json'),
  '54_12': () => require('./tiles/tile_54_12.json'),
  '54_13': () => require('./tiles/tile_54_13.json'),
  '54_14': () => require('./tiles/tile_54_14.json'),
  '54_15': () => require('./tiles/tile_54_15.json'),
  '54_16': () => require('./tiles/tile_54_16.json'),
  '54_17': () => require('./tiles/tile_54_17.json'),
  '54_7': () => require('./tiles/tile_54_7.json'),
  '54_8': () => require('./tiles/tile_54_8.json'),
  '54_9': () => require('./tiles/tile_54_9.json'),
  '55_10': () => require('./tiles/tile_55_10.json'),
  '55_11': () => require('./tiles/tile_55_11.json'),
  '55_12': () => require('./tiles/tile_55_12.json'),
  '55_13': () => require('./tiles/tile_55_13.json'),
  '55_14': () => require('./tiles/tile_55_14.json'),
  '55_15': () => require('./tiles/tile_55_15.json'),
  '55_8': () => require('./tiles/tile_55_8.json'),
  '55_9': () => require('./tiles/tile_55_9.json'),
};

/**
 * Returns the tile keys needed to cover a ~25km radius around the given coordinates.
 */
function getNeededTileKeys(lat: number, lon: number): string[] {
  const keys: string[] = [];
  // Load the tile containing the point plus all 8 neighbors
  const baseLat = Math.floor(lat);
  const baseLon = Math.floor(lon);
  for (let dLat = -1; dLat <= 1; dLat++) {
    for (let dLon = -1; dLon <= 1; dLon++) {
      const key = `${baseLat + dLat}_${baseLon + dLon}`;
      if (tileMap[key]) keys.push(key);
    }
  }
  return keys;
}

/**
 * Loads toilets from relevant tiles near the given coordinates.
 */
export function loadNearbyTiles(lat: number, lon: number): RawToilet[] {
  const keys = getNeededTileKeys(lat, lon);
  const all: RawToilet[] = [];
  for (const key of keys) {
    all.push(...tileMap[key]());
  }
  return all;
}
